import { IPersonalScore } from '../_models/interfaces/personal-score.interface';

export const PERSONAL_SCORES: IPersonalScore[] = [
    {
        examinee: 'Laila Piraino',
        analyticalAbilityValue: 84,
        quickThinkingValue: 27,
        performanceUnderPreassureValue: 84,
        adaptabilityValue: 27,
        averageScoreValue: 84,
        completionValue: 54,
        color: '',
    },
    {
        examinee: 'Queen Rudy',
        analyticalAbilityValue: 12,
        quickThinkingValue: 69,
        performanceUnderPreassureValue: 45,
        adaptabilityValue: 99,
        averageScoreValue: 66,
        completionValue: 90,
        color: '',
    },
    {
        examinee: 'Lavera Lettieri',
        analyticalAbilityValue: 24,
        quickThinkingValue: 26,
        performanceUnderPreassureValue: 77,
        adaptabilityValue: 49,
        averageScoreValue: 56,
        completionValue: 49,
        color: '',
    },
    {
        examinee: 'Oliver Parada',
        analyticalAbilityValue: 39,
        quickThinkingValue: 56,
        performanceUnderPreassureValue: 98,
        adaptabilityValue: 59,
        averageScoreValue: 26,
        completionValue: 48,
        color: '',
    },
    {
        examinee: 'Joanie Koeller',
        analyticalAbilityValue: 47,
        quickThinkingValue: 27,
        performanceUnderPreassureValue: 99,
        adaptabilityValue: 48,
        averageScoreValue: 37,
        completionValue: 44,
        color: '',
    },
    {
        examinee: 'Shirl Daffron',
        analyticalAbilityValue: 58,
        quickThinkingValue: 29,
        performanceUnderPreassureValue: 89,
        adaptabilityValue: 17,
        averageScoreValue: 28,
        completionValue: 49,
        color: '',
    },
    {
        examinee: 'Genaro Stgelais',
        analyticalAbilityValue: 37,
        quickThinkingValue: 44,
        performanceUnderPreassureValue: 30,
        adaptabilityValue: 60,
        averageScoreValue: 28,
        completionValue: 59,
        color: '',
    },
    {
        examinee: 'Alysa Feola',
        analyticalAbilityValue: 84,
        quickThinkingValue: 95,
        performanceUnderPreassureValue: 53,
        adaptabilityValue: 95,
        averageScoreValue: 62,
        completionValue: 55,
        color: '',
    },
    {
        examinee: 'Rossana Fremont',
        analyticalAbilityValue: 42,
        quickThinkingValue: 86,
        performanceUnderPreassureValue: 94,
        adaptabilityValue: 97,
        averageScoreValue: 55,
        completionValue: 42,
        color: '',
    },
    {
        examinee: 'Warner Miceli',
        analyticalAbilityValue: 64,
        quickThinkingValue: 99,
        performanceUnderPreassureValue: 52,
        adaptabilityValue: 95,
        averageScoreValue: 63,
        completionValue: 77,
        color: '',
    },
    {
        examinee: 'Bobbye Rocco',
        analyticalAbilityValue: 66,
        quickThinkingValue: 42,
        performanceUnderPreassureValue: 77,
        adaptabilityValue: 58,
        averageScoreValue: 73,
        completionValue: 87,
        color: '',
    },
    {
        examinee: 'Abram Stanback',
        analyticalAbilityValue: 65,
        quickThinkingValue: 99,
        performanceUnderPreassureValue: 76,
        adaptabilityValue: 72,
        averageScoreValue: 44,
        completionValue: 57,
        color: '',
    },
    {
        examinee: 'Deonna Spargo',
        analyticalAbilityValue: 73,
        quickThinkingValue: 73,
        performanceUnderPreassureValue: 77,
        adaptabilityValue: 97,
        averageScoreValue: 32,
        completionValue: 44,
        color: '',
    },
    {
        examinee: 'Kaitlyn Dimery',
        analyticalAbilityValue: 68,
        quickThinkingValue: 86,
        performanceUnderPreassureValue: 75,
        adaptabilityValue: 75,
        averageScoreValue: 57,
        completionValue: 98,
        color: '',
    },
    {
        examinee: 'Cyndi Mitchem',
        analyticalAbilityValue: 68,
        quickThinkingValue: 78,
        performanceUnderPreassureValue: 68,
        adaptabilityValue: 77,
        averageScoreValue: 11,
        completionValue: 68,
        color: '',
    },
    {
        examinee: 'Deshawn Mcnealy',
        analyticalAbilityValue: 68,
        quickThinkingValue: 25,
        performanceUnderPreassureValue: 54,
        adaptabilityValue: 54,
        averageScoreValue: 5,
        completionValue: 3,
        color: '',
    },
    {
        examinee: 'Raylene Amore',
        analyticalAbilityValue: 7,
        quickThinkingValue: 8,
        performanceUnderPreassureValue: 5,
        adaptabilityValue: 1,
        averageScoreValue: 2,
        completionValue: 6,
        color: '',
    },
    {
        examinee: 'Magali Abel',
        analyticalAbilityValue: 86,
        quickThinkingValue: 75,
        performanceUnderPreassureValue: 33,
        adaptabilityValue: 58,
        averageScoreValue: 45,
        completionValue: 76,
        color: '',
    },
    {
        examinee: 'Burton Dreiling',
        analyticalAbilityValue: 75,
        quickThinkingValue: 74,
        performanceUnderPreassureValue: 69,
        adaptabilityValue: 96,
        averageScoreValue: 86,
        completionValue: 75,
        color: '',
    },
    {
        examinee: 'Kandy Mayhugh',
        analyticalAbilityValue: 76,
        quickThinkingValue: 58,
        performanceUnderPreassureValue: 69,
        adaptabilityValue: 82,
        averageScoreValue: 53,
        completionValue: 36,
        color: '',
    },
    {
        examinee: 'Coreen Trainor',
        analyticalAbilityValue: 56,
        quickThinkingValue: 77,
        performanceUnderPreassureValue: 86,
        adaptabilityValue: 86,
        averageScoreValue: 99,
        completionValue: 57,
        color: '',
    },
    {
        examinee: 'Jose Winborne',
        analyticalAbilityValue: 75,
        quickThinkingValue: 96,
        performanceUnderPreassureValue: 75,
        adaptabilityValue: 85,
        averageScoreValue: 33,
        completionValue: 63,
        color: '',
    },
    {
        examinee: 'Denver Grissett',
        analyticalAbilityValue: 58,
        quickThinkingValue: 86,
        performanceUnderPreassureValue: 96,
        adaptabilityValue: 86,
        averageScoreValue: 77,
        completionValue: 96,
        color: '',
    },
    {
        examinee: 'Latoya Corrigan',
        analyticalAbilityValue: 75,
        quickThinkingValue: 47,
        performanceUnderPreassureValue: 11,
        adaptabilityValue: 96,
        averageScoreValue: 69,
        completionValue: 66,
        color: '',
    },
    {
        examinee: 'Delores Bettes',
        analyticalAbilityValue: 85 ,
        quickThinkingValue: 65,
        performanceUnderPreassureValue: 85,
        adaptabilityValue: 77,
        averageScoreValue: 22,
        completionValue: 36,
        color: '',
    },
    {
        examinee: 'Cleopatra Mabrey',
        analyticalAbilityValue: 74,
        quickThinkingValue: 58,
        performanceUnderPreassureValue: 75,
        adaptabilityValue: 22,
        averageScoreValue: 51,
        completionValue: 36,
        color: '',
    },
    {
        examinee: 'Lavina Matte',
        analyticalAbilityValue: 25,
        quickThinkingValue: 78,
        performanceUnderPreassureValue: 75,
        adaptabilityValue: 96,
        averageScoreValue: 47,
        completionValue: 53,
        color: '',
    },
    {
        examinee: 'Suzanna Hutcheson',
        analyticalAbilityValue: 58,
        quickThinkingValue: 96,
        performanceUnderPreassureValue: 68,
        adaptabilityValue: 68,
        averageScoreValue: 77,
        completionValue: 42,
        color: '',
    },
    {
        examinee: 'Loriann Trego',
        analyticalAbilityValue: 89,
        quickThinkingValue: 78,
        performanceUnderPreassureValue: 86,
        adaptabilityValue: 96,
        averageScoreValue: 88,
        completionValue: 75,
        color: '',
    },
    {
        examinee: 'Brandee Italiano',
        analyticalAbilityValue: 74,
        quickThinkingValue: 75,
        performanceUnderPreassureValue: 78,
        adaptabilityValue: 87,
        averageScoreValue: 78,
        completionValue: 58,
        color: '',
    },
    {
        examinee: 'Sherrell Lall',
        analyticalAbilityValue: 47,
        quickThinkingValue: 14,
        performanceUnderPreassureValue: 14,
        adaptabilityValue: 1,
        averageScoreValue: 33,
        completionValue: 69,
        color: '',
    },
    {
        examinee: 'Carylon Brannock',
        analyticalAbilityValue: 36,
        quickThinkingValue: 36,
        performanceUnderPreassureValue: 36,
        adaptabilityValue: 99,
        averageScoreValue: 57,
        completionValue: 47,
        color: '',
    },
    {
        examinee: 'Genaro Stgelais',
        analyticalAbilityValue: 75,
        quickThinkingValue: 17,
        performanceUnderPreassureValue: 74,
        adaptabilityValue: 36,
        averageScoreValue: 96,
        completionValue: 58,
        color: '',
    },
    {
        examinee: 'Alysa Feola',
        analyticalAbilityValue: 27,
        quickThinkingValue: 75,
        performanceUnderPreassureValue: 86,
        adaptabilityValue: 5,
        averageScoreValue: 46,
        completionValue: 65,
        color: '',
    },
    {
        examinee: 'Rossana Fremont',
        analyticalAbilityValue: 87,
        quickThinkingValue: 86,
        performanceUnderPreassureValue: 86,
        adaptabilityValue: 77,
        averageScoreValue: 98,
        completionValue: 78,
        color: '',
    },
    {
        examinee: 'Warner Miceli',
        analyticalAbilityValue: 87,
        quickThinkingValue: 66,
        performanceUnderPreassureValue: 65,
        adaptabilityValue: 53,
        averageScoreValue: 88,
        completionValue: 77,
        color: '',
    },
    {
        examinee: 'Bobbye Rocco',
        analyticalAbilityValue: 87,
        quickThinkingValue: 84,
        performanceUnderPreassureValue: 64,
        adaptabilityValue: 65,
        averageScoreValue: 98,
        completionValue: 86,
        color: '',
    },
    {
        examinee: 'Abram Stanback',
        analyticalAbilityValue: 76,
        quickThinkingValue: 65,
        performanceUnderPreassureValue: 43,
        adaptabilityValue: 21,
        averageScoreValue: 11,
        completionValue: 34,
        color: '',
    },
    {
        examinee: 'Deonna Spargo',
        analyticalAbilityValue: 65,
        quickThinkingValue: 43,
        performanceUnderPreassureValue: 52,
        adaptabilityValue: 35,
        averageScoreValue: 98,
        completionValue: 57,
        color: '',
    },
    {
        examinee: 'Kaitlyn Dimery',
        analyticalAbilityValue: 76,
        quickThinkingValue: 44,
        performanceUnderPreassureValue: 87,
        adaptabilityValue: 97,
        averageScoreValue: 65,
        completionValue: 65,
        color: '',
    },
    {
        examinee: 'Cyndi Mitchem',
        analyticalAbilityValue: 76,
        quickThinkingValue: 85,
        performanceUnderPreassureValue: 64,
        adaptabilityValue: 88,
        averageScoreValue: 36,
        completionValue: 66,
        color: '',
    },
    {
        examinee: 'Deshawn Mcnealy',
        analyticalAbilityValue: 5,
        quickThinkingValue: 3,
        performanceUnderPreassureValue: 5,
        adaptabilityValue: 6,
        averageScoreValue: 74,
        completionValue: 44,
        color: '',
    },
    {
        examinee: 'Raylene Amore',
        analyticalAbilityValue: 65,
        quickThinkingValue: 75,
        performanceUnderPreassureValue: 66,
        adaptabilityValue: 86,
        averageScoreValue: 77,
        completionValue: 35,
        color: '',
    },
    {
        examinee: 'Magali Abel',
        analyticalAbilityValue: 64,
        quickThinkingValue: 64,
        performanceUnderPreassureValue: 77,
        adaptabilityValue: 96,
        averageScoreValue: 66,
        completionValue: 37,
        color: '',
    },
    {
        examinee: 'Burton Dreiling',
        analyticalAbilityValue: 94,
        quickThinkingValue: 64,
        performanceUnderPreassureValue: 85,
        adaptabilityValue: 75,
        averageScoreValue: 63,
        completionValue: 22,
        color: '',
    },
    {
        examinee: 'Kandy Mayhugh',
        analyticalAbilityValue: 12,
        quickThinkingValue: 15,
        performanceUnderPreassureValue: 54,
        adaptabilityValue: 76,
        averageScoreValue: 86,
        completionValue: 64,
        color: '',
    },
    {
        examinee: 'Coreen Trainor',
        analyticalAbilityValue: 75,
        quickThinkingValue: 77,
        performanceUnderPreassureValue: 53,
        adaptabilityValue: 76,
        averageScoreValue: 64,
        completionValue: 67,
        color: '',
    },
    {
        examinee: 'Jose Winborne',
        analyticalAbilityValue: 74,
        quickThinkingValue: 68,
        performanceUnderPreassureValue: 64,
        adaptabilityValue: 69,
        averageScoreValue: 43,
        completionValue: 56,
        color: '',
    },
    {
        examinee: 'Denver Grissett',
        analyticalAbilityValue: 54,
        quickThinkingValue: 86,
        performanceUnderPreassureValue: 64,
        adaptabilityValue: 74,
        averageScoreValue: 59,
        completionValue: 69,
        color: '',
    },
    {
        examinee: 'Latoya Corrigan',
        analyticalAbilityValue: 69,
        quickThinkingValue: 47,
        performanceUnderPreassureValue: 58,
        adaptabilityValue: 36,
        averageScoreValue: 57,
        completionValue: 36,
        color: '',
    },
    {
        examinee: 'Delores Bettes',
        analyticalAbilityValue: 57,
        quickThinkingValue: 48,
        performanceUnderPreassureValue: 57,
        adaptabilityValue: 58,
        averageScoreValue: 4,
        completionValue: 89,
        color: '',
    }
];
